#!/usr/bin/env bash
#
# A wizard — walks a human through setting up higher API rate limits
# for image-fetcher. Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.
#

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

TOTAL_STAGES=0
TOTAL_MINUTES=0

_STAGE_INDEX=0
_MINUTES_ELAPSED=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()
WRITTEN_SECRET=()
SKIPPED=()

_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages · about %s minutes%s\n\n' \
    "$DIM" "$TOTAL_STAGES" "$TOTAL_MINUTES" "$RESET"
  printf '%s  This wizard grabs free API credentials so image-fetcher gets higher\n' "$DIM"
  printf '  rate limits (Openverse: 200/day -> 10,000/day). All keys are optional —\n'
  printf '  the skill works keyless by default. Stop any time with Ctrl-C.%s\n' "$RESET"
  pause "Ready to start?"
}

stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  local remaining=$((TOTAL_MINUTES - _MINUTES_ELAPSED))
  (( remaining < 0 )) && remaining=0
  _MINUTES_ELAPSED=$((_MINUTES_ELAPSED + ${2:-0}))
  printf '\n%s%s▸ Stage %s/%s · %s%s  %s(~%s min left)%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET" "$DIM" "$remaining" "$RESET"
}

say()  { printf '  %s\n' "$1"; }
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES
# ──────────────────────────────────────────────────────────────────────────

CONFIG_DIR="$HOME/.config/image-fetcher"
ENV_FILE="$CONFIG_DIR/.env"
mkdir -p "$CONFIG_DIR"

TOTAL_STAGES=3
TOTAL_MINUTES=8

banner "image-fetcher — higher rate limits"

# ── Stage 1: Openverse registration ──────────────────────────────────────
stage "Openverse — register app" 4

say "Openverse boosts from 200 requests/day (anonymous) to 10,000/day (authenticated)."
say "The API is fully functional without this — only set it up if you hit rate limits."
echo

if ! confirm "Set up Openverse authentication?"; then
  note "Skipping Openverse — staying keyless (200/day)."
  SKIPPED+=("Openverse auth (keyless mode)")
else
  step "This registers an app programmatically. You'll need an email address."
  echo
  ask OV_EMAIL "Your email (for Openverse verification):"

  if [[ -z "$OV_EMAIL" ]]; then
    warn "No email provided — skipping Openverse."
    SKIPPED+=("Openverse auth (no email)")
  else
    note "Registering app 'image-fetcher' with Openverse..."
    REG_RESPONSE=$(curl -sS -X POST "https://api.openverse.org/v1/auth_tokens/register/" \
      -H "Content-Type: application/json" \
      -d "{\"name\":\"image-fetcher-$RANDOM\",\"description\":\"image-fetcher skill\",\"email\":\"$OV_EMAIL\"}" 2>&1)

    OV_CLIENT_ID=$(echo "$REG_RESPONSE" | python3 -c "import sys,json;d=json.load(sys.stdin);print(d.get('client_id',''))" 2>/dev/null || echo "")
    OV_CLIENT_SECRET=$(echo "$REG_RESPONSE" | python3 -c "import sys,json;d=json.load(sys.stdin);print(d.get('client_secret',''))" 2>/dev/null || echo "")

    if [[ -z "$OV_CLIENT_ID" || -z "$OV_CLIENT_SECRET" ]]; then
      warn "Registration didn't return credentials. Response:"
      note "$REG_RESPONSE"
      SKIPPED+=("Openverse auth (registration failed)")
    else
      note "Registered! A verification link was sent to $OV_EMAIL."
      echo
      open_url "https://mail.google.com"
      step "Open your email and click the Openverse verification link."
      step "Come back here after clicking it."
      pause "Clicked the verification link?"

      note "Testing credentials..."
      TOKEN_RESP=$(curl -sS -X POST "https://api.openverse.org/v1/auth_tokens/token/" \
        -H "Content-Type: application/x-www-form-urlencoded" \
        -d "client_id=$OV_CLIENT_ID&client_secret=$OV_CLIENT_SECRET&grant_type=client_credentials" 2>&1)

      TOKEN_OK=$(echo "$TOKEN_RESP" | python3 -c "import sys,json;d=json.load(sys.stdin);print('ok' if 'access_token' in d else d.get('error','failed'))" 2>/dev/null || echo "failed")

      if [[ "$TOKEN_OK" == "ok" ]]; then
        write_env OPENVERSE_CLIENT_ID "$OV_CLIENT_ID"
        write_env OPENVERSE_CLIENT_SECRET "$OV_CLIENT_SECRET"
        note "Credentials verified — 10,000 requests/day unlocked."
      else
        warn "Token exchange failed: $TOKEN_OK"
        note "The credentials were saved anyway — you may need to re-verify your email."
        write_env OPENVERSE_CLIENT_ID "$OV_CLIENT_ID"
        write_env OPENVERSE_CLIENT_SECRET "$OV_CLIENT_SECRET"
        SKIPPED+=("Openverse token verification (check email)")
      fi
    fi
  fi
fi

# ── Stage 2: Wikimedia (optional) ───────────────────────────────────────
stage "Wikimedia — bot password (optional)" 3

say "Wikimedia bot auth raises concurrency limits and reduces throttling."
say "The skill works fine without this (maxlag + polite delays handle it)."
echo

if ! confirm "Set up Wikimedia authentication?"; then
  note "Skipping Wikimedia — using keyless with maxlag."
  SKIPPED+=("Wikimedia auth (keyless with maxlag)")
else
  open_url "https://commons.wikimedia.org/wiki/Special:BotPasswords"
  step "Log in to Wikimedia Commons if prompted."
  step "Enter a bot name (e.g. 'image-fetcher') and create it."
  step "Check these permissions: High-volume (bot), Existing, Edit existing."
  step "You'll get a password (shown once). Copy it."
  echo
  ask WM_BOT_USER "Bot login username (e.g. YourName@image-fetcher):"
  ask_secret WM_BOT_PASS "Bot password:"

  if [[ -z "$WM_BOT_USER" || -z "$WM_BOT_PASS" ]]; then
    warn "Missing credentials — skipping Wikimedia."
    SKIPPED+=("Wikimedia auth (incomplete)")
  else
    write_env WIKIMEDIA_BOT_USER "$WM_BOT_USER"
    write_env WIKIMEDIA_BOT_PASS "$WM_BOT_PASS"
    note "Credentials saved — higher Wikimedia limits active."
  fi
fi

# ── Stage 3: Summary ────────────────────────────────────────────────────
stage "Done" 1

note "Config written to: $ENV_FILE"
note "image-fetcher reads this automatically on every run."
echo
if [[ -f "$ENV_FILE" ]]; then
  note "Current config keys:"
  while IFS='=' read -r key _; do
    note "  - $key"
  done < "$ENV_FILE"
fi
echo
say "You can re-run this wizard any time to update credentials."
say "To go back to keyless mode, delete: rm $ENV_FILE"

finish
